name: Send Email via Thunderbird

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
          docker build -t thunderbird-email .

      - name: Run the Docker container
        run: |
          docker run --rm thunderbird-email
