name: Sendmail with Python

on:
  push:
    branches:
      - main

jobs:
  test-email:
    runs-on: ubuntu-latest

    services:
      sendmail:
        image: catatnight/sendmail:latest
        ports:
          - 25:25 # Sendmail listens on port 25

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install smtplib

      - name: Run Python Script
        run: python send_email.py
